---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
#  no_log: "{{ molecule_no_log }}"
  module_defaults:
    group/gcp:
      project: "{{ molecule_yml.driver.gcp_project_id }}"
      auth_kind: serviceaccount
      service_account_file: "{{ molecule_yml.driver.gcp_service_account_key }}"
  tasks:
    - name: create network resources
      include_tasks: tasks/create_network.yml

    - name: create instances
      include_tasks: tasks/create_instance.yml
      loop: "{{ molecule_yml.platforms }}"

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.name }}",
          'address': "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}",
          'user': "{{ molecule_yml.driver.ssh_user }}",
          'port': "22",
          'identity_file': "{{ molecule_yml.driver.ssh_key_file }}", }
      with_items: "{{ instance_created.instances }}"
      register: instance_config_dict
      when: instance_created.changed

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: instance_created.changed

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: instance_created.changed
