---
language: python
python:
  - "3.6"

env:
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/secret.json SSH_USER=mpisellonio SSH_ID_FILE=$TRAVIS_BUILD_DIR/.ssh/id_rsa

before_install:
  # decrypt service-account-key
  - openssl aes-256-cbc -K $encrypted_297aa543cc91_key -iv $encrypted_297aa543cc91_iv -in ${GOOGLE_APPLICATION_CREDENTIALS}.enc -out ${GOOGLE_APPLICATION_CREDENTIALS} -d

install:
  # install molecule and docker
  - pip install molecule ansible-lint flake8

  # generate ssh key
  - ssh-keygen -P '' -f ${SSH_ID_FILE} -C ${SSH_USER}

  # install role prerequisites
#  - ansible-galaxy install nephelaiio.docker

script:
  - molecule --version
  - ansible --version
  - molecule test
